import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const target = path.join(root, '.env');
const args = Object.fromEntries(process.argv.slice(2).map((arg) => {
  const [key, ...rest] = arg.replace(/^--/, '').split('=');
  return [key, rest.join('=')];
}));
const truthy = (value) => ['1', 'true', 'yes', 'on'].includes(String(value || '').toLowerCase());
const randomSecret = () => crypto.randomBytes(48).toString('base64url');
const randomPassword = () => `MT-${crypto.randomBytes(12).toString('base64url')}!9a`;

const production = truthy(args.production);
const baseUrl = args['base-url'] || (production ? '' : 'http://localhost:3000');
const adminPassword = args['admin-password'] || 'VercelChangeMe-Now-2026!';
const adminEmail = (args['admin-email'] || 'admin@example.com').trim().toLowerCase();
const whatsapp = String(args.whatsapp || '').replace(/\D/g, '');
const notificationEmail = String(args['notification-email'] || '').trim();
const enforceCampaign = args['campaign-enforce'] === undefined ? production : truthy(args['campaign-enforce']);

let existingDatabaseUrl = args['database-url'] || '';
if (fs.existsSync(target)) {
  const envContent = fs.readFileSync(target, 'utf8');
  const match = envContent.match(/^DATABASE_URL=(.+)$/m);
  if (match) {
    existingDatabaseUrl = match[1].replace(/(^"|"$|^'|'$)/g, '');
  }
}

if (fs.existsSync(target) && !truthy(args.force)) {
  console.error('.env already exists. Use --force=1 only when you intentionally want to replace it.');
  process.exit(1);
}
if (production && !/^https:\/\//i.test(baseUrl)) {
  console.error('Production setup requires --base-url=https://your-production-domain');
  process.exit(1);
}
if (!adminEmail || !adminEmail.includes('@')) {
  console.error('A valid --admin-email is required.');
  process.exit(1);
}
if (adminPassword.length < 12) {
  console.error('--admin-password must contain at least 12 characters.');
  process.exit(1);
}

let content = `# Generated by npm run setup. Do not commit this file.\nNODE_ENV=${production ? 'production' : 'development'}\nAPP_VERSION=1.0.0\nPORT=3000\nTRUST_PROXY=${production ? 1 : 0}\nAPP_BASE_URL=${baseUrl}\nFRONTEND_DEV_ORIGIN=http://localhost:5173\nDATABASE_PATH=backend/data/mama-time.json\nJWT_SECRET=${randomSecret()}\nIP_HASH_SECRET=${randomSecret()}\nADMIN_COOKIE_NAME=mt_admin_token\nADMIN_TOKEN_HOURS=8\nADMIN_BOOTSTRAP_EMAIL=${adminEmail}\nADMIN_BOOTSTRAP_PASSWORD=${adminPassword}\nADMIN_BOOTSTRAP_NAME=Sentinators Admin\nSHOW_DEFAULT_PASSWORD_WARNING=false\nCAMPAIGN_ENFORCE=${enforceCampaign}\nCAMPAIGN_START=2026-07-20T00:00:00+02:00\nCAMPAIGN_END=2026-08-20T23:59:59+02:00\nCAMPAIGN_TIMEZONE=Europe/Zurich\nSINGLE_PRICE_CHF=550\nBESTIES_PRICE_CHF=990\nDAYTIME_HOURS=Montag bis Freitag, 08:00–16:30 Uhr\nWHATSAPP_NUMBER=${whatsapp}\nWHATSAPP_MESSAGE=Hallo Sentinators Gym, ich interessiere mich für die MAMA TIME Aktion.\nNOTIFICATION_EMAIL=${notificationEmail}\nSMTP_HOST=\nSMTP_PORT=587\nSMTP_SECURE=false\nSMTP_USER=\nSMTP_PASSWORD=\nSMTP_FROM=Sentinators Gym <website@example.ch>\nPUBLIC_RATE_LIMIT_WINDOW_MINUTES=15\nPUBLIC_RATE_LIMIT_MAX=8\nPUBLIC_MIN_FORM_SECONDS=2\nDUPLICATE_WINDOW_HOURS=24\nALLOW_DESTRUCTIVE_RESET=false\n`;

if (existingDatabaseUrl) {
  content += `DATABASE_URL="${existingDatabaseUrl}"\n`;
}


fs.writeFileSync(target, content, { mode: 0o600 });
console.log('');
console.log('MAMA TIME environment created successfully.');
console.log(`Mode: ${production ? 'production' : 'development'}`);
console.log(`Application URL: ${baseUrl}`);
console.log(`Admin URL: ${baseUrl}/admin`);
console.log(`Admin email: ${adminEmail}`);
console.log(`Admin password: ${adminPassword}`);
console.log('');
console.log('Store the password in a password manager. It will be used only when the first admin account is created.');
console.log('Next commands: npm run build && npm start');
