import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const target = path.join(root, '.env');
const args = Object.fromEntries(process.argv.slice(2).map((arg) => {
  const [key, ...rest] = arg.replace(/^--/, '').split('=');
  return [key, rest.join('=')];
}));
const truthy = (value) => ['1', 'true', 'yes', 'on'].includes(String(value || '').toLowerCase());
const randomSecret = () => crypto.randomBytes(48).toString('base64url');
// const randomPassword = (prefix = 'MT') => `${prefix}-${crypto.randomBytes(15).toString('base64url')}!9a`;

const production = truthy(args.production);
const docker = truthy(args.docker);
const baseUrl = args['base-url'] || (production ? '' : 'http://localhost:3000');
const adminPassword = args['admin-password'] || 'ChangeMe-Now-2026!';
const adminEmail = (args['admin-email'] || (production ? '' : 'admin@sentinators.local')).trim().toLowerCase();
const whatsapp = String(args.whatsapp || '').replace(/\D/g, '');
const notificationEmail = String(args['notification-email'] || '').trim();
const enforceCampaign = args['campaign-enforce'] === undefined ? production : truthy(args['campaign-enforce']);
const postgresPassword = args['postgres-password'] || 'ChangeMe-Now-2026!';
const databaseUrl = args['database-url'] || `postgresql://mama_time:${encodeURIComponent(postgresPassword)}@127.0.0.1:5432/mama_time`;
const dockerDatabaseUrl = args['database-url-docker'] || `postgresql://mama_time:${encodeURIComponent(postgresPassword)}@db:5432/mama_time`;

if (fs.existsSync(target) && !truthy(args.force)) {
  console.error('.env already exists. Use --force=1 only when you intentionally want to replace it.');
  process.exit(1);
}
if (production && !/^https:\/\//i.test(baseUrl)) {
  console.error('Production setup requires --base-url=https://your-production-domain');
  process.exit(1);
}
if (!adminEmail || !adminEmail.includes('@')) {
  console.error('A valid --admin-email is required.');
  process.exit(1);
}
if (adminPassword.length < 12) {
  console.error('--admin-password must contain at least 12 characters.');
  process.exit(1);
}
if (!/^postgres(?:ql)?:\/\//i.test(databaseUrl)) {
  console.error('--database-url must be a valid PostgreSQL connection URL.');
  process.exit(1);
}
if (production && !args['database-url'] && !docker) {
  console.error('Production setup requires --database-url=postgresql://... or --docker=1.');
  process.exit(1);
}

const content = `# Generated by npm run setup. Do not commit this file.\nNODE_ENV=${production ? 'production' : 'development'}\nAPP_VERSION=2.1.0\nPORT=3000\nTRUST_PROXY=${production ? 1 : 0}\nAPP_BASE_URL=${baseUrl}\nFRONTEND_DEV_ORIGIN=http://localhost:5173\nDATABASE_URL=${databaseUrl}\nDATABASE_URL_DOCKER=${dockerDatabaseUrl}\nDATABASE_SSL=false\nDATABASE_SSL_REJECT_UNAUTHORIZED=true\nDATABASE_POOL_MAX=10\nDATABASE_IDLE_TIMEOUT_MS=30000\nDATABASE_CONNECTION_TIMEOUT_MS=10000\nRUN_MIGRATIONS_ON_START=true\nDATABASE_LOG_QUERIES=false\nDATABASE_USE_PGMEM=false\nPOSTGRES_DB=mama_time\nPOSTGRES_USER=mama_time\nPOSTGRES_PASSWORD=${postgresPassword}\nJWT_SECRET=${randomSecret()}\nIP_HASH_SECRET=${randomSecret()}\nADMIN_COOKIE_NAME=mt_admin_token\nADMIN_TOKEN_HOURS=8\nADMIN_BOOTSTRAP_EMAIL=${adminEmail}\nADMIN_BOOTSTRAP_PASSWORD=${adminPassword}\nADMIN_BOOTSTRAP_NAME=Sentinators Admin\nSHOW_DEFAULT_PASSWORD_WARNING=false\nCAMPAIGN_ENFORCE=${enforceCampaign}\nCAMPAIGN_START=2026-07-20T00:00:00+02:00\nCAMPAIGN_END=2026-08-20T23:59:59+02:00\nCAMPAIGN_TIMEZONE=Europe/Zurich\nSINGLE_PRICE_CHF=550\nBESTIES_PRICE_CHF=990\nDAYTIME_HOURS=Montag bis Freitag, 08:00–16:30 Uhr\nWHATSAPP_NUMBER=${whatsapp}\nWHATSAPP_MESSAGE=Hallo Sentinators Gym, ich interessiere mich für die MAMA TIME Aktion.\nNOTIFICATION_EMAIL=${notificationEmail}\nMETA_PIXEL_ENABLED=false\nMETA_PIXEL_ID=\nSMTP_HOST=\nSMTP_PORT=587\nSMTP_SECURE=false\nSMTP_USER=\nSMTP_PASSWORD=\nSMTP_FROM=Sentinator GmbH <info@sentinator.li>\nPUBLIC_RATE_LIMIT_WINDOW_MINUTES=15\nPUBLIC_RATE_LIMIT_MAX=8\nPUBLIC_MIN_FORM_SECONDS=2\nDUPLICATE_WINDOW_HOURS=24\nALLOW_DESTRUCTIVE_RESET=false\nALLOW_DESTRUCTIVE_RESTORE=false\nALLOW_JSON_IMPORT=false\n`;

fs.writeFileSync(target, content, { mode: 0o600 });
console.log('');
console.log('MAMA TIME PostgreSQL environment created successfully.');
console.log(`Mode: ${production ? 'production' : 'development'}`);
console.log(`Application URL: ${baseUrl}`);
console.log(`Admin URL: ${baseUrl}/admin`);
console.log(`Admin email: ${adminEmail}`);
console.log(`Admin password: ${adminPassword}`);
console.log(`PostgreSQL user: mama_time`);
console.log(`PostgreSQL password: ${postgresPassword}`);
console.log('');
console.log('Store both passwords in a password manager.');
if (docker) {
  console.log('Next command: docker compose up -d --build');
} else {
  console.log('Next commands: npm run db:migrate && npm run build && npm start');
}
